filegroup(
    name = "tests",
    srcs = ["//python/clients/tests:detect_objects"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "services",
    srcs = ["//python/clients/services:detect_objects",
            "//python/clients/services:visualize_dataset",
            "//python/clients/services:grade_dataset",
           ],
    visibility = ["//visibility:public"],
)
