# resources for label_reader unit tests

filegroup(
  name = "jsons",
  srcs = [
      "jsons/label_reader_params.json",
      "jsons/label_reader_params_grocery.json",
  ],
  visibility = ["//visibility:public"],
)

