filegroup(
    name = "datastructs",
    srcs = ["//python/bnr/datastructs:api"],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "datastructs_test",
    tests = ["//python/bnr/datastructs/test:test"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "object_detection",
    srcs = ["//python/bnr/object_detection:api"],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "object_detection_test",
    tests = ["//python/bnr/object_detection/test:test"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "metrics",
    srcs = ["//python/bnr/metrics:api"],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "metrics_test",
    tests = ["//python/bnr/metrics/test:test"],
    visibility = ["//visibility:public"],
)
